//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using BlogPost.Models.BlogHome;

[assembly: RegisterDocumentType(BlogHome.CLASS_NAME, typeof(BlogHome))]

namespace BlogPost.Models.BlogHome
{
	/// <summary>
	/// Represents a content item of type BlogHome.
	/// </summary>
	public partial class BlogHome : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "BlogPost.BlogHome";


		/// <summary>
		/// The instance of the class that provides extended API for working with BlogHome fields.
		/// </summary>
		private readonly BlogHomeFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// BlogHomeID.
		/// </summary>
		[DatabaseIDField]
		public int BlogHomeID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("BlogHomeID"), 0);
			}
			set
			{
				SetValue("BlogHomeID", value);
			}
		}


		/// <summary>
		/// BlogHomeTitle.
		/// </summary>
		[DatabaseField]
		public string BlogHomeTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BlogHomeTitle"), @"");
			}
			set
			{
				SetValue("BlogHomeTitle", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with BlogHome fields.
		/// </summary>
		[RegisterProperty]
		public BlogHomeFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with BlogHome fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class BlogHomeFields : AbstractHierarchicalObject<BlogHomeFields>
		{
			/// <summary>
			/// The content item of type BlogHome that is a target of the extended API.
			/// </summary>
			private readonly BlogHome mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="BlogHomeFields" /> class with the specified content item of type BlogHome.
			/// </summary>
			/// <param name="instance">The content item of type BlogHome that is a target of the extended API.</param>
			public BlogHomeFields(BlogHome instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// BlogHomeID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.BlogHomeID;
				}
				set
				{
					mInstance.BlogHomeID = value;
				}
			}


			/// <summary>
			/// BlogHomeTitle.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.BlogHomeTitle;
				}
				set
				{
					mInstance.BlogHomeTitle = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="BlogHome" /> class.
		/// </summary>
		public BlogHome() : base(CLASS_NAME)
		{
			mFields = new BlogHomeFields(this);
		}

		#endregion
	}
}