//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.HouseRestaurant;

[assembly: RegisterDocumentType(DishSubCategory.CLASS_NAME, typeof(DishSubCategory))]

namespace CMS.DocumentEngine.Types.HouseRestaurant
{
	/// <summary>
	/// Represents a content item of type DishSubCategory.
	/// </summary>
	public partial class DishSubCategory : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "HouseRestaurant.DishSubCategory";


		/// <summary>
		/// The instance of the class that provides extended API for working with DishSubCategory fields.
		/// </summary>
		private readonly DishSubCategoryFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// DishSubCategoryID.
		/// </summary>
		[DatabaseIDField]
		public int DishSubCategoryID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("DishSubCategoryID"), 0);
			}
			set
			{
				SetValue("DishSubCategoryID", value);
			}
		}


		/// <summary>
		/// Element Id.
		/// </summary>
		[DatabaseField]
		public string ElementId
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ElementId"), @"");
			}
			set
			{
				SetValue("ElementId", value);
			}
		}


		/// <summary>
		/// Css Class.
		/// </summary>
		[DatabaseField]
		public string CssClass
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CssClass"), @"");
			}
			set
			{
				SetValue("CssClass", value);
			}
		}


		/// <summary>
		/// Url.
		/// </summary>
		[DatabaseField]
		public string Url
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Url"), @"");
			}
			set
			{
				SetValue("Url", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with DishSubCategory fields.
		/// </summary>
		[RegisterProperty]
		public DishSubCategoryFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with DishSubCategory fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class DishSubCategoryFields : AbstractHierarchicalObject<DishSubCategoryFields>
		{
			/// <summary>
			/// The content item of type DishSubCategory that is a target of the extended API.
			/// </summary>
			private readonly DishSubCategory mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="DishSubCategoryFields" /> class with the specified content item of type DishSubCategory.
			/// </summary>
			/// <param name="instance">The content item of type DishSubCategory that is a target of the extended API.</param>
			public DishSubCategoryFields(DishSubCategory instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// DishSubCategoryID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.DishSubCategoryID;
				}
				set
				{
					mInstance.DishSubCategoryID = value;
				}
			}


			/// <summary>
			/// Element Id.
			/// </summary>
			public string ElementId
			{
				get
				{
					return mInstance.ElementId;
				}
				set
				{
					mInstance.ElementId = value;
				}
			}


			/// <summary>
			/// Css Class.
			/// </summary>
			public string CssClass
			{
				get
				{
					return mInstance.CssClass;
				}
				set
				{
					mInstance.CssClass = value;
				}
			}


			/// <summary>
			/// Url.
			/// </summary>
			public string Url
			{
				get
				{
					return mInstance.Url;
				}
				set
				{
					mInstance.Url = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="DishSubCategory" /> class.
		/// </summary>
		public DishSubCategory() : base(CLASS_NAME)
		{
			mFields = new DishSubCategoryFields(this);
		}

		#endregion
	}
}