//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.HouseRestaurant;

[assembly: RegisterDocumentType(DishCategory.CLASS_NAME, typeof(DishCategory))]

namespace CMS.DocumentEngine.Types.HouseRestaurant
{
	/// <summary>
	/// Represents a content item of type DishCategory.
	/// </summary>
	public partial class DishCategory : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "HouseRestaurant.DishCategory";


		/// <summary>
		/// The instance of the class that provides extended API for working with DishCategory fields.
		/// </summary>
		private readonly DishCategoryFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// DishCategoryID.
		/// </summary>
		[DatabaseIDField]
		public int DishCategoryID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("DishCategoryID"), 0);
			}
			set
			{
				SetValue("DishCategoryID", value);
			}
		}


		/// <summary>
		/// Element Id.
		/// </summary>
		[DatabaseField]
		public string ElementId
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ElementId"), @"");
			}
			set
			{
				SetValue("ElementId", value);
			}
		}


		/// <summary>
		/// Css Class.
		/// </summary>
		[DatabaseField]
		public string CssClass
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CssClass"), @"");
			}
			set
			{
				SetValue("CssClass", value);
			}
		}


		/// <summary>
		/// Url.
		/// </summary>
		[DatabaseField]
		public string Url
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Url"), @"");
			}
			set
			{
				SetValue("Url", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with DishCategory fields.
		/// </summary>
		[RegisterProperty]
		public DishCategoryFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with DishCategory fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class DishCategoryFields : AbstractHierarchicalObject<DishCategoryFields>
		{
			/// <summary>
			/// The content item of type DishCategory that is a target of the extended API.
			/// </summary>
			private readonly DishCategory mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="DishCategoryFields" /> class with the specified content item of type DishCategory.
			/// </summary>
			/// <param name="instance">The content item of type DishCategory that is a target of the extended API.</param>
			public DishCategoryFields(DishCategory instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// DishCategoryID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.DishCategoryID;
				}
				set
				{
					mInstance.DishCategoryID = value;
				}
			}


			/// <summary>
			/// Element Id.
			/// </summary>
			public string ElementId
			{
				get
				{
					return mInstance.ElementId;
				}
				set
				{
					mInstance.ElementId = value;
				}
			}


			/// <summary>
			/// Css Class.
			/// </summary>
			public string CssClass
			{
				get
				{
					return mInstance.CssClass;
				}
				set
				{
					mInstance.CssClass = value;
				}
			}


			/// <summary>
			/// Url.
			/// </summary>
			public string Url
			{
				get
				{
					return mInstance.Url;
				}
				set
				{
					mInstance.Url = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="DishCategory" /> class.
		/// </summary>
		public DishCategory() : base(CLASS_NAME)
		{
			mFields = new DishCategoryFields(this);
		}

		#endregion
	}
}