//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.HouseRestaurant;

[assembly: RegisterDocumentType(MenuItem.CLASS_NAME, typeof(MenuItem))]

namespace CMS.DocumentEngine.Types.HouseRestaurant
{
	/// <summary>
	/// Represents a content item of type MenuItem.
	/// </summary>
	public partial class MenuItem : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "HouseRestaurant.MenuItem";


		/// <summary>
		/// The instance of the class that provides extended API for working with MenuItem fields.
		/// </summary>
		private readonly MenuItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// MenuItemID.
		/// </summary>
		[DatabaseIDField]
		public int MenuItemID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("MenuItemID"), 0);
			}
			set
			{
				SetValue("MenuItemID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Url.
		/// </summary>
		[DatabaseField]
		public string Url
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Url"), @"");
			}
			set
			{
				SetValue("Url", value);
			}
		}


		/// <summary>
		/// Enabled.
		/// </summary>
		[DatabaseField]
		public bool Enabled
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Enabled"), true);
			}
			set
			{
				SetValue("Enabled", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with MenuItem fields.
		/// </summary>
		[RegisterProperty]
		public MenuItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with MenuItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class MenuItemFields : AbstractHierarchicalObject<MenuItemFields>
		{
			/// <summary>
			/// The content item of type MenuItem that is a target of the extended API.
			/// </summary>
			private readonly MenuItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="MenuItemFields" /> class with the specified content item of type MenuItem.
			/// </summary>
			/// <param name="instance">The content item of type MenuItem that is a target of the extended API.</param>
			public MenuItemFields(MenuItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// MenuItemID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.MenuItemID;
				}
				set
				{
					mInstance.MenuItemID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// Url.
			/// </summary>
			public string Url
			{
				get
				{
					return mInstance.Url;
				}
				set
				{
					mInstance.Url = value;
				}
			}


			/// <summary>
			/// Enabled.
			/// </summary>
			public bool Enabled
			{
				get
				{
					return mInstance.Enabled;
				}
				set
				{
					mInstance.Enabled = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="MenuItem" /> class.
		/// </summary>
		public MenuItem() : base(CLASS_NAME)
		{
			mFields = new MenuItemFields(this);
		}

		#endregion
	}
}