//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.HouseRestaurant;

[assembly: RegisterDocumentType(SecondaryMenuItem.CLASS_NAME, typeof(SecondaryMenuItem))]

namespace CMS.DocumentEngine.Types.HouseRestaurant
{
	/// <summary>
	/// Represents a content item of type SecondaryMenuItem.
	/// </summary>
	public partial class SecondaryMenuItem : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "HouseRestaurant.SecondaryMenuItem";


		/// <summary>
		/// The instance of the class that provides extended API for working with SecondaryMenuItem fields.
		/// </summary>
		private readonly SecondaryMenuItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// SecondaryMenuItemID.
		/// </summary>
		[DatabaseIDField]
		public int SecondaryMenuItemID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("SecondaryMenuItemID"), 0);
			}
			set
			{
				SetValue("SecondaryMenuItemID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Url.
		/// </summary>
		[DatabaseField]
		public string Url
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Url"), @"");
			}
			set
			{
				SetValue("Url", value);
			}
		}


		/// <summary>
		/// IsEnabled.
		/// </summary>
		[DatabaseField]
		public bool IsEnabled
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("IsEnabled"), true);
			}
			set
			{
				SetValue("IsEnabled", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with SecondaryMenuItem fields.
		/// </summary>
		[RegisterProperty]
		public SecondaryMenuItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with SecondaryMenuItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class SecondaryMenuItemFields : AbstractHierarchicalObject<SecondaryMenuItemFields>
		{
			/// <summary>
			/// The content item of type SecondaryMenuItem that is a target of the extended API.
			/// </summary>
			private readonly SecondaryMenuItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="SecondaryMenuItemFields" /> class with the specified content item of type SecondaryMenuItem.
			/// </summary>
			/// <param name="instance">The content item of type SecondaryMenuItem that is a target of the extended API.</param>
			public SecondaryMenuItemFields(SecondaryMenuItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// SecondaryMenuItemID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.SecondaryMenuItemID;
				}
				set
				{
					mInstance.SecondaryMenuItemID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// Url.
			/// </summary>
			public string Url
			{
				get
				{
					return mInstance.Url;
				}
				set
				{
					mInstance.Url = value;
				}
			}


			/// <summary>
			/// IsEnabled.
			/// </summary>
			public bool IsEnabled
			{
				get
				{
					return mInstance.IsEnabled;
				}
				set
				{
					mInstance.IsEnabled = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="SecondaryMenuItem" /> class.
		/// </summary>
		public SecondaryMenuItem() : base(CLASS_NAME)
		{
			mFields = new SecondaryMenuItemFields(this);
		}

		#endregion
	}
}